### ISSUE TITLE
Add examples on how to create filters objects

### ISSUE THREAD

**Issue by rgosse** [activeviam/react-api-documenter#43]
The actual filter object is more complex than the doc suggests:

```
 {
        dimensionName: "Currency",
        hierarchyName: "Currency",
        type: "members",
        members: [["AllMember", "USD"]],
      }
```

When the doc just says `Filter on currency = USD`.

To help users, we should document filter objects more thoroughly.

**Comment by Nouzbe** [comment]
I believe that this is a request to improve this page: https://activeviam.com/activeui/documentation/latest/docs/api/types#filteronmembers.

This page is maintained on the ActiveUI repository (not open source) and cannot be improved directly within https://github.com/activeviam/react-api-documenter.
